mypos:
  api:
    url: https://www.mypos.com/vmp/checkout-test
  lang: en
  key-index: 2
  sid: 1025856
  wallet-number: 40321005262
  version: 1.4
  keys:
    publicKey: |
      -----BEGIN PUBLIC KEY-----
      MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDEGDCEMfmsDKEoPubWnAVaLm7l
      K47iL5uzVXdb3IoY1FgAl779uY/F0zM8sji+gbcyC4u4KSaQ0EvXXUdFUlRo/BEU
      juzZ+a9L9Zh3NAyvo8zmQZc17CuHGAucIrXcsX30Xq3CUdSUcT+Vm3GgvnETpVCG
      237y9A80TRzQ7obhtQIDAQAB
      -----END PUBLIC KEY-----
    privateKey: |
      -----BEGIN PRIVATE KEY-----
      MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAMoUNocNYl/b5M4X
      Ft7euaQEdBOCMq25CggQpNv0h8UboNhyoucz0HGgSMeBqdlSYxkWqx560LWu4SFS
      ehVSf4w0HJlEgyMIXIkQ8UY5NZ8XMHfGIBaDI1715BBtjrjnuedp76YAi5IEabRF
      9s0EoWSCLen5mGg1vieKJWxvEQqBAgMBAAECgYBTdMmYOQTZxfzWyF5fqOhOPrCZ
      pfm8GWF1Nzp+xJyV4PUqrx1sEtARPTsRehFleUsH/36oVdyATDsaAe/9gla+GkUW
      c4PBzI5gKZQppoo78NSx9o7XGMaCL+X9CzKtuN3lY/RsVXcf0dWElJQzBhAEHOgV
      Ta5YvbzNR7XWw9GQ4QJBAPH00gvfkuORReIhMNiRyCfdRvWb4czGtCiQ+iixJUXg
      WVyJ6TzGAsz7LApez1yodD5uJCoByM/uiTfjGQVCacUCQQDVztzgDMjL3WWS6sNs
      cfOfF9dm+PG7XBcw5oivXorNayxi/1HKrnMxGdaMDt4GYD24Sw32JNp+JGmYd6XH
      qzWNAkAQXcALf47/B6eTeS1FqO7CC4yuNmIaqOIs0EmrkPf1dwx0XvvA2Z/834yG
      Ew2xtc9PHcIieUZtEjSD7D+YBHsFAkAuYNj4oM1Nq5DE9be+Zll6QSmwZH/LLIa7
      TMaJg/CH7p+KOef8FytVk00+xFrU9ztsJpu4sPXUNwHQ2ONVFIZhAkEAvvP7hv9z
      HH9Eb19fsssKe+0F2ZfSSS8g7FzDhSxvonF5v42pXsAwLuIhgRBHtUS3z8zZ4tam
      4x1voxcjoTILug==
      -----END PRIVATE KEY-----

