mypos:
  api:
    url: https://www.mypos.com/vmp/checkout-test
  lang: en
  key-index: 1
  sid: 000000000000010
  wallet-number: 61938166610
  version: 1.4
  keys:
    publicKey: |
      -----BEGIN PUBLIC KEY-----
      MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDC/lU5omOMgoaDkzGU1wCBv5pP
      sX//Zo8B8Vs8bQSWzZ3DStDiyNFV2ClthoFZJRhx0I73sNYUxZBBo5wie3+Qg524
      MXr7cgEgxrLfdmusXAHnRGnT9JxV4VM/nGGCICHIHw3F92VnjRBeZLHKsudpKQ9j
      u5xTQlfvOb0uHbiQTQIDAQAB
      -----END PUBLIC KEY-----
    privateKey: |
      -----BEGIN PRIVATE KEY-----
      MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAJ/RN1xO6mFvtf5n
      B6S3VcoRZkNzNIZ5x+jq9B+q+tp/lU/NycnYxzknvYcGbS73wQkdqf6eV7ZY5kxU
      Yi1Nr/aTUVFbBu3uJDl3MOHk8R5kBKDZRZ6GhHwvwyk0GofqHtkhPBVN9FLguwG+
      UR9Ps/OGblgkp8z4J3MMz4v1ZUQbAgMBAAECgYBh8rHBS0Rury6VWsPeedaEX6GT
      WTop6N1SrR0tg3b3DxaNsIwpv0hqiSapaJDmJkYStjGHsbgEM/wBb/4z0dcziiqb
      lISRrGFtOWCSz4TWz11Ol0VC8vvpO+h2pLKXYTYGCFWAsuCR2FGf1u5oXNi1r3kk
      p+DIoaic3GxADf0/AQJBAMpsbQqnooSQ2AGysKrcLHah3k5+I8MbyDdFhkrH8710
      zLkIzXrQPC6xUmm7LBulGFxaveCTPRCBEx0hFXDLE1sCQQDKHeyKmZyA3tIPzEEb
      8y0Fg+pY/W/GFJVg98nO49TeBLkxEnNAcHOxUIuFMFjuEdKiqKqWpZhqyLzUnMET
      AS5BAkEArD2oZxmPIwfwlTlMNIaWWvePJvEUUw+PxOAmzfjoAHyjOosv9OG9Y+nE
      e20lsfxAB027JZ2Dp0h9UBr3mHtj4wJARmCNEOXUHPt5YY7ZzQWr05PPchUtameY
      bB9b4fJrGLPEWFX4U6PUZRWKv2HKVXtXQNRCMhqPK/+h4NaEVD3BAQJALJ2Eno1o
      1A4JmH7pBOsfdMLkx4EDVh6Kmh7v4GGws2twUbyz2xPFGeW1xmXV1doFJ6a+k28G
      LOfQrOLwbdkCBw==
      -----END PRIVATE KEY-----

